version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3002
      - ACCESS_TOKEN_SECRET=your_access_token_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - GLOBAL_TOKEN_SECRET=your_global_token_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_REDIRECT_URL=https://your_redirect_url
      - GOOGLE_REFRESH_TOKEN=your_google_refresh_token
      - GOOGLE_USER_EMAIL=your_email@example.com
      - GOOGLE_AUTH_CLIENT_ID=your_google_auth_client_id
      - GOOGLE_AUTH_CLIENT_SECRET=your_google_auth_client_secret
      - GOOGLE_AUTH_REDIRECT_URL=http://localhost:3001/api/google/redirect
      - GOOGLE_ACCOUNT_SERVICE_CLIENT_EMAIL=your_service_account_email
      - GOOGLE_ACCOUNT_SERVICE_PRIVATE_KEY=your_private_key
      - GOOGLE_DRIVE_FOLDER_ID=your_google_drive_folder_id
      - REDIS_URL=redis://redis:6379
      - REDIS_TTL=300000
      - MONGODB_URI=mongodb+srv://your_mongo_user:your_mongo_password@your_mongo_cluster/your_database?retryWrites=true&w=majority&appName=your_app_name
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    environment:
      // copy from .env.example file

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: your_secure_password
    command: ["redis-server", "--requirepass", "your_secure_password"]
