version: '3.8'

services:
  app:
    container_name: backend_road_pothole_detection
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ../.env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis_service_road_pothole_detection
    image: redis:latest
    command: [ "redis-server", "--requirepass", "your_secure_password" ]
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  redis_data:


networks:
  app-network:
    driver: bridge
