name: Pull images and Run on VPS

on:
  pull_request:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4.2.2

      - name: "Shut down containers if there's any"
        working-directory: docker/
        run: docker-compose down

      - name: "Run docker-compose file"
        working-directory: docker/
        run: docker-compose up -d