name: Build and Publish Docker Image

on:
  push:
    branches:
      - main 
      - deploy/docker-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Create a new builder instance
        run: docker buildx create --use --name mybuilder

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: buithiendev/road-pohole-detechion-backend:latest
          
      - name: Log out of Docker Hub
        run: docker logout
